(defun bichu-color-theme ()
  (interactive)
  (color-theme-install
   '(bichu-color-theme
      ((background-color . "#141414")
      (background-mode . light)
      (border-color . "#2e2e2e")
      (cursor-color . "#ad9090")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#141414"))))
     (mode-line ((t (:foreground "#000000" :background "#4a4a4a"))))
     (region ((t (:background "#3a3a3a"))))
     (font-lock-builtin-face ((t (:foreground "#0c8d39"))))
     (font-lock-comment-face ((t (:foreground "#7c6e6e"))))
     (font-lock-function-name-face ((t (:foreground "#5066d7"))))
     (font-lock-keyword-face ((t (:foreground "#afd1f8"))))
     (font-lock-string-face ((t (:foreground "#5bd77f"))))
     (font-lock-type-face ((t (:foreground"#3d9537"))))
     (font-lock-variable-name-face ((t (:foreground "#ded95e"))))
     (minibuffer-prompt ((t (:foreground "#7299ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'bichu-color-theme)